### ISSUE TITLE
[Todo] General

### ISSUE THREAD

**Issue by zaydek** [feathericons/feathericons.dev#25]
- [x] Integrate new `prose` lib
- [x] Integrate new `lib` utilities
- [x] Do Duomo CSS-based examples
- [x] Prototype sidebar
- [x] Prototype sticky nav
- [x] Prototype icon page
